### ISSUE TITLE
its not support ruby 3. because of : ruby_dep-1.5.0

### ISSUE THREAD

**Issue by sg552** [dkubb/memoizable#26]
```
Query List: ["memoizable"]
Query Gemcutter Dependency Endpoint API: memoizable
HTTP GET https://gems.ruby-china.com/api/v1/dependencies?gems=memoizable
HTTP 200 OK https://gems.ruby-china.com/api/v1/dependencies?gems=memoizable
Query List: []
Resolving dependencies....
ruby_dep-1.5.0 requires ruby version ~> 2.2, >= 2.2.5, which is incompatible with the current version, ruby 3.0.3p157
Bundler::InstallError: ruby_dep-1.5.0 requires ruby version ~> 2.2, >= 2.2.5, which is incompatible with the current version, ruby 3.0.3p157
/home/siwei/.asdf/installs/ruby/3.0.3/lib/ruby/3.0.0/bundler/installer.rb:249:in `block in ensure_specs_are_compatible!'
  /home/siwei/.asdf/installs/ruby/3.0.3/lib/ruby/3.0.0/bundler/spec_set.rb:136:in `each'
  /home/siwei/.asdf/installs/ruby/3.0.3/lib/ruby/3.0.0/bundler/spec_set.rb:136:in `each'
  /home/siwei/.asdf/installs/ruby/3.0.3/lib/ruby/3.0.0/bundler/installer.rb:246:in `ensure_specs_are_compatible!'
  /home/siwei/.asdf/installs/ruby/3.0.3/lib/ruby/3.0.0/bundler/installer.rb:83:in `block in run'
  /home/siwei/.asdf/installs/ruby/3.0.3/lib/ruby/3.0.0/bundler/process_lock.rb:12:in `block in lock'
  /home/siwei/.asdf/installs/ruby/3.0.3/lib/ruby/3.0.0/bundler/process_lock.rb:9:in `open'
  /home/siwei/.asdf/installs/ruby/3.0.3/lib/ruby/3.0.0/bundler/process_lock.rb:9:in `lock'
  /home/siwei/.asdf/installs/ruby/3.0.3/lib/ruby/3.0.0/bundler/installer.rb:71:in `run'
  /home/siwei/.asdf/installs/ruby/3.0.3/lib/ruby/3.0.0/bundler/installer.rb:23:in `install'
  /home/siwei/.asdf/installs/ruby/3.0.3/lib/ruby/3.0.0/bundler/cli/install.rb:60:in `run'
  /home/siwei/.asdf/installs/ruby/3.0.3/lib/ruby/3.0.0/bundler/cli.rb:253:in `block in install'
  /home/siwei/.asdf/installs/ruby/3.0.3/lib/ruby/3.0.0/bundler/settings.rb:131:in `temporary'
  /home/siwei/.asdf/installs/ruby/3.0.3/lib/ruby/3.0.0/bundler/cli.rb:252:in `install'
  /home/siwei/.asdf/installs/ruby/3.0.3/lib/ruby/3.0.0/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
  /home/siwei/.asdf/installs/ruby/3.0.3/lib/ruby/3.0.0/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
  /home/siwei/.asdf/installs/ruby/3.0.3/lib/ruby/3.0.0/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
  /home/siwei/.asdf/installs/ruby/3.0.3/lib/ruby/3.0.0/bundler/cli.rb:31:in `dispatch'
  /home/siwei/.asdf/installs/ruby/3.0.3/lib/ruby/3.0.0/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
  /home/siwei/.asdf/installs/ruby/3.0.3/lib/ruby/3.0.0/bundler/cli.rb:25:in `start'
  /home/siwei/.asdf/installs/ruby/3.0.3/lib/ruby/gems/3.0.0/gems/bundler-2.2.32/libexec/bundle:49:in `block in <top (required)>'
  /home/siwei/.asdf/installs/ruby/3.0.3/lib/ruby/3.0.0/bundler/friendly_errors.rb:103:in `with_friendly_errors'
  /home/siwei/.asdf/installs/ruby/3.0.3/lib/ruby/gems/3.0.0/gems/bundler-2.2.32/libexec/bundle:37:in `<top (required)>'
  /home/siwei/.asdf/installs/ruby/3.0.3/bin/bundle:23:in `load'
  /home/siwei/.asdf/installs/ruby/3.0.3/bin/bundle:23:in `<main>'

```

**Comment by dkubb** [comment]
I removed support for Ruby versions that are EOL. I'd accept a patch to re-add support for these (and enable it in CI again), but I don't use any EOL ruby versions anymore.
